services:
  - type: web
    name: pdf-to-barcode
    runtime: python

    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: PATH
        value: /usr/lib/jvm/java-17-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    buildCommand: |
      apt-get update
      apt-get install -y openjdk-17-jre-headless
      pip install -r requirements.txt

    startCommand: python app.py
