services:
  - type: web
    name: pdf-to-barcode
    env: python
    pythonVersion: 3.11
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-17-jre-headless
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      pip install -r requirements.txt
    startCommand: python app.py
